INICIO: 	MOV EAX 0x01
		MOV EDX, DS
		LDL ECX,1
		LDH ECX,4
		SYS 1
		MOV [ECX], [EDX]
		CMP ECX,1
		JZ FIN
		CMP ECX, 2
		JZ FIN
		MOV [EEX], [ECX]
		DIV EEX,2
DIVIDO:DIV ECX, EEX
		CMP AC,0
		JZ ESPRIMO
		SUB EEX, 1
		CMP EEX, 2
		JZ NOESPRIMO
		JMP DIVIDO
NOESPRIMO:MOV [EDX],0
		JMP FIN
ESPRIMO:MOV [EDX],1
FIN:MOV EDX,DS
		MOV EAX,0x01
		LDL ECX,1
		LDH ECX,4
		SYS 2
		STOP
//Dado un número natural, imprimir un 1 si es primo y un 0 si no lo es.
